# Generated by Django 5.2.15 on 2026-07-31 19:18

import django.utils.timezone
import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tickets', '0008_user_first_access_new_hierarchy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', tickets.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='changelog',
            name='entity_type',
            field=models.CharField(choices=[('USER', 'Usuário'), ('ANNOUNCEMENT', 'Comunicado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='area',
            field=models.CharField(blank=True, choices=[('DIRETORIA', 'Diretoria'), ('VICE_DIRETORIA', 'Vice-diretoria'), ('SECRETARIA', 'Secretaria'), ('STAI', 'Stai'), ('COORDENACAO_PEDAGOGICA', 'Coordenação pedagógica')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Aberto'), ('IN_PROGRESS', 'Em tratativa'), ('FORWARDED', 'Encaminhado'), ('CLOSED', 'Encerrado'), ('DONE', 'Concluído')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketevent',
            name='from_status',
            field=models.CharField(blank=True, choices=[('OPEN', 'Aberto'), ('IN_PROGRESS', 'Em tratativa'), ('FORWARDED', 'Encaminhado'), ('CLOSED', 'Encerrado'), ('DONE', 'Concluído')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketevent',
            name='kind',
            field=models.CharField(choices=[('COMMENT', 'Comentário'), ('STATUS', 'Mudança de status'), ('TRANSFER', 'Transferencia'), ('REOPEN', 'Reabertura')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketevent',
            name='to_status',
            field=models.CharField(blank=True, choices=[('OPEN', 'Aberto'), ('IN_PROGRESS', 'Em tratativa'), ('FORWARDED', 'Encaminhado'), ('CLOSED', 'Encerrado'), ('DONE', 'Concluído')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='area',
            field=models.CharField(blank=True, choices=[('DIRETORIA', 'Diretoria'), ('VICE_DIRETORIA', 'Vice-diretoria'), ('SECRETARIA', 'Secretaria'), ('STAI', 'Stai'), ('COORDENACAO_PEDAGOGICA', 'Coordenação pedagógica')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='vinculo',
            field=models.CharField(choices=[('ADMINISTRATIVO', 'Funcionário administrativo'), ('PROFESSOR', 'Professor')], default='ADMINISTRATIVO', max_length=40),
        ),
    ]
