# Generated by Django 5.2.15 on 2026-07-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Edição'), ('PASSWORD', 'Troca de senha'), ('FIRST_ACCESS_PASSWORD', 'Troca de senha no primeiro acesso'), ('ACTIVATE', 'Ativação'), ('DEACTIVATE', 'Inativação'), ('PUBLISH', 'Publicação'), ('UNPUBLISH', 'Despublicação')], max_length=40),
        ),
    ]
